### ISSUE TITLE
No options to configure RDS region

### ISSUE THREAD

**Issue by bharath5412** [labd/django-iam-dbauth#2]
in `base.py`, while creating a boto3 client object for the region is specified implicitly and read from configuration file (~/.aws/config in UNIX or LINUX) or from environment variable. Unfortunately, this is difficult to read in django/apache setup because of multiple processes spawning to serve the request (the environment variables are not passed to sub-processes spawned). It would be great if the region can be specified in the `DATABASES` setting in Django settings.

**Comment by mikedingjan** [comment]
Region name is added via PR: #3
