### ISSUE TITLE
breakpoint in utils.py causing an error

### ISSUE THREAD

**Issue by russau** [labd/django-iam-dbauth#40]
Hello, it looks like this breakpoint code was included in the `0.2.0` release today.

It is causing a problem for me when I installed django-iam-dbauth from pip today.

https://github.com/labd/django-iam-dbauth/blob/c5a72ac3ee4d4e4fafd0b06b1acd805219f7b326/src/django_iam_dbauth/utils.py#L17

**Comment by pjstevns** [comment]
I'll fix. Just ran into it as well.

**Comment by pjstevns** [comment]
update package 0.2.1 was just released
