### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by han-so1omon** [labd/django-iam-dbauth#7]
This package is really nice and could be quite useful. I keep seeing that IAM authentication is one of the recommended methods for connecting with and operating RDS databases.

Is this still maintained by @n4cr or @mvantellingen ? I see PR #6 is open, and I think it should be merged.

**Comment by n4cr** [comment]
@mvantellingen has the access to merge the PR

**Comment by mvantellingen** [comment]
Yeah good point. We are actually also migrating most of our projects to rds-proxy with IAM information. We will follow-up asap

**Comment by nicois** [comment]
This might be work forking, it's been a few weeks now.

**Comment by mikedingjan** [comment]
The PR #3  is merged now together with a better Github actions workflow which makes creating releases easier as well
